In [1]:
import pandas as pd
data=pd.read_csv('student_performance_500.csv')
data

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result
0,STU001,Anu Nair,Female,20,CSE,81.1,78.7,82.0,3.5,0,75.2,Pass
1,STU002,Arun Pillai,Male,22,MCA,96.4,87.2,96.2,5.6,1,78.3,Pass
2,STU003,Meera Das,Male,21,EEE,75.2,87.2,85.2,7.5,1,70.0,Pass
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass
4,STU005,Diya Kumar,Male,20,CSE,81.6,68.0,75.3,2.3,0,65.0,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...
495,STU496,Devika Joseph,Male,20,EEE,88.7,85.6,74.8,4.9,0,68.9,Pass
496,STU497,Gokul George,Female,21,CSE,80.6,78.4,72.4,4.4,0,67.5,Pass
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass
498,STU499,Kiran Thomas,Male,23,MCA,79.9,85.4,79.0,5.4,0,75.7,Pass
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass

In [3]:
print(data.isnull().values.any())

False

In [4]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [5]:
data=data.drop_duplicates()

In [8]:
print(data.duplicated())

0      False
1      False
2      False
3      False
4      False
       ...
495    False
496    False
497    False
498    False
499    False
Length: 500, dtype: bool

In [11]:
data['Attendance']=data['Attendance'].fillna(data['Attendance'].median())

In [13]:
print(
    data[data["Final_Mark"] > 80][
        ["Student_ID", "Name", "Final_Mark"]
    ]
)

    Student_ID           Name  Final_Mark
3       STU004   Rahul Sharma        83.5
5       STU006   Akhil Joseph        80.2
6       STU007    Asha George        88.6
18      STU019   Kiran Thomas        82.9
25      STU026    Hari Joseph        87.2
..         ...            ...         ...
482     STU483      Meera Das        81.2
484     STU485     Diya Kumar        81.5
487     STU488   Vishnu Menon        87.0
493     STU494  Athira Sharma       100.0
494     STU495  Adithya Kumar        81.9

[98 rows x 3 columns]

In [ ]:
print(
    data[data["Final_Mark"] < 75][
        ["Student_ID", "Name", "Final_Mark"]
    ]
)

In [18]:
backlog_student=data[data['Backlogs']>0]
print(backlog_student)

    Student_ID           Name  Gender  Age Department  Attendance  \
1       STU002    Arun Pillai    Male   22        MCA        96.4
2       STU003      Meera Das    Male   21        EEE        75.2
11      STU012  Anjali Pillai    Male   23        ECE        63.1
12      STU013      Arjun Das  Female   22        CSE        77.5
13      STU014  Athira Sharma    Male   20         ME        57.8
..         ...            ...     ...  ...        ...         ...
479     STU480  Abhinav Varma  Female   21        ECE        69.0
484     STU485     Diya Kumar    Male   21         ME        94.4
485     STU486   Akhil Joseph    Male   22        ECE        82.2
488     STU489    Neha Thomas    Male   22        MCA        84.4
490     STU491      Amal Nair    Male   20         CE        87.7

     Assignment_Score  Internal_Mark  Study_Hours  Backlogs  Final_Mark Result
1                87.2           96.2          5.6         1        78.3   Pass
2                87.2           85.2          7.5         1        70.0   Pass
11               75.5           85.4          5.7         1        64.7   Pass
12               85.6           75.8          4.3         1        77.0   Pass
13               83.2           87.8          5.3         2        58.1   Pass
..                ...            ...          ...       ...         ...    ...
479              78.4           71.7          3.9         1        61.4   Pass
484              83.3           91.1          6.5         1        81.5   Pass
485              72.6           66.4          4.4         1        60.4   Pass
488              72.2           77.1          2.9         4        53.1   Pass
490              81.0           69.0          3.4         1        65.1   Pass

[180 rows x 12 columns]

In [19]:
print(data[data['Backlogs']>0]['Name'])

1        Arun Pillai
2          Meera Das
11     Anjali Pillai
12         Arjun Das
13     Athira Sharma
           ...
479    Abhinav Varma
484       Diya Kumar
485     Akhil Joseph
488      Neha Thomas
490        Amal Nair
Name: Name, Length: 180, dtype: object

In [32]:
print(data[data["Result"] =="Pass"]['Name'])

0           Anu Nair
1        Arun Pillai
2          Meera Das
3       Rahul Sharma
4         Diya Kumar
           ...
495    Devika Joseph
496     Gokul George
497      Kavya Menon
498     Kiran Thomas
499       Maya Varma
Name: Name, Length: 489, dtype: object

In [27]:
passed_students = data[data["Result"] == "Pass"]

print(passed_students)

    Student_ID           Name  Gender  Age Department  Attendance  \
0       STU001       Anu Nair  Female   20        CSE        81.1
1       STU002    Arun Pillai    Male   22        MCA        96.4
2       STU003      Meera Das    Male   21        EEE        75.2
3       STU004   Rahul Sharma    Male   21        ECE       100.0
4       STU005     Diya Kumar    Male   20        CSE        81.6
..         ...            ...     ...  ...        ...         ...
495     STU496  Devika Joseph    Male   20        EEE        88.7
496     STU497   Gokul George  Female   21        CSE        80.6
497     STU498    Kavya Menon  Female   19        CSE        69.8
498     STU499   Kiran Thomas    Male   23        MCA        79.9
499     STU500     Maya Varma    Male   23        EEE        73.5

     Assignment_Score  Internal_Mark  Study_Hours  Backlogs  Final_Mark Result
0                78.7           82.0          3.5         0        75.2   Pass
1                87.2           96.2          5.6         1        78.3   Pass
2                87.2           85.2          7.5         1        70.0   Pass
3                84.6           88.7          5.2         0        83.5   Pass
4                68.0           75.3          2.3         0        65.0   Pass
..                ...            ...          ...       ...         ...    ...
495              85.6           74.8          4.9         0        68.9   Pass
496              78.4           72.4          4.4         0        67.5   Pass
497              83.4           73.6          5.0         0        65.1   Pass
498              85.4           79.0          5.4         0        75.7   Pass
499              71.3           74.2          5.7         0        67.4   Pass

[489 rows x 12 columns]

In [43]:
data['Average_score']=(data['Assignment_Score']+data['Internal_Mark']+data['Final_Mark'])/3
data

,Student_ID,Name,Gender,Age,Department,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Result,Average_score
0,STU001,Anu Nair,Female,20,CSE,81.1,78.7,82.0,3.5,0,75.2,Pass,78.633333
1,STU002,Arun Pillai,Male,22,MCA,96.4,87.2,96.2,5.6,1,78.3,Pass,87.233333
2,STU003,Meera Das,Male,21,EEE,75.2,87.2,85.2,7.5,1,70.0,Pass,80.800000
3,STU004,Rahul Sharma,Male,21,ECE,100.0,84.6,88.7,5.2,0,83.5,Pass,85.600000
4,STU005,Diya Kumar,Male,20,CSE,81.6,68.0,75.3,2.3,0,65.0,Pass,69.433333
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,STU496,Devika Joseph,Male,20,EEE,88.7,85.6,74.8,4.9,0,68.9,Pass,76.433333
496,STU497,Gokul George,Female,21,CSE,80.6,78.4,72.4,4.4,0,67.5,Pass,72.766667
497,STU498,Kavya Menon,Female,19,CSE,69.8,83.4,73.6,5.0,0,65.1,Pass,74.033333
498,STU499,Kiran Thomas,Male,23,MCA,79.9,85.4,79.0,5.4,0,75.7,Pass,80.033333
499,STU500,Maya Varma,Male,23,EEE,73.5,71.3,74.2,5.7,0,67.4,Pass,70.966667

In [45]:
department_count=data.groupby('Department')['Student_ID'].count()
print(department_count)

Department
CE      81
CSE    157
ECE     76
EEE     72
MCA     53
ME      61
Name: Student_ID, dtype: int64

In [47]:
gender_count=data.groupby('Gender')['Student_ID'].count()
print(gender_count)

Gender
Female    237
Male      263
Name: Student_ID, dtype: int64

In [50]:
gender_name=data.groupby('Gender')['Name'].apply(list)
print(gender_name)

Gender
Female    [Anu Nair, Asha George, Neha Thomas, Nikhil Va...
Male      [Arun Pillai, Meera Das, Rahul Sharma, Diya Ku...
Name: Name, dtype: object

In [51]:
sorted_students=data.sort_values(by='Final_Mark',ascending=False)
print(sorted_students)

    Student_ID           Name  Gender  Age Department  Attendance  \
447     STU448  Sreeram Menon  Female   21        MCA        87.6
493     STU494  Athira Sharma  Female   20         CE        85.8
32      STU033      Meera Das    Male   19        CSE       100.0
85      STU086    Hari Joseph    Male   20        ECE        95.8
151     STU152    Arun Pillai    Male   20        CSE        85.6
..         ...            ...     ...  ...        ...         ...
299     STU300  Abhinav Varma  Female   19        CSE        72.8
321     STU322  Sanjay Pillai    Male   21        CSE        68.7
198     STU199   Kiran Thomas    Male   22         CE        68.1
442     STU443      Sneha Das  Female   20        ECE        67.8
14      STU015  Adithya Kumar    Male   20        CSE        66.2

     Assignment_Score  Internal_Mark  Study_Hours  Backlogs  Final_Mark  \
447             100.0          100.0          8.5         0       100.0
493             100.0          100.0         10.0         0       100.0
32               97.6           99.7          8.2         1        98.6
85               92.0          100.0          6.7         0        96.8
151              97.3          100.0         10.0         2        95.4
..                ...            ...          ...       ...         ...
299              56.0           59.0          1.6         0        45.5
321              68.5           61.3          1.9         1        45.0
198              65.0           64.7          1.0         0        44.9
442              53.4           59.7          1.7         0        43.1
14               62.0           57.2          2.9         1        41.9

    Result  Average_score
447   Pass     100.000000
493   Pass     100.000000
32    Pass      98.633333
85    Pass      96.266667
151   Pass      97.566667
..     ...            ...
299   Fail      53.500000
321   Fail      58.266667
198   Fail      58.200000
442   Fail      52.066667
14    Fail      53.700000

[500 rows x 13 columns]

In [52]:
data.describe()

,Age,Attendance,Assignment_Score,Internal_Mark,Study_Hours,Backlogs,Final_Mark,Average_score
count,500.000000,500.0000,500.000000,500.000000,500.000000,500.000000,500.000000,500.000000
mean,20.588000,82.6102,78.879000,80.437800,4.597200,0.454000,70.901200,76.739333
std,1.062315,9.7273,10.021763,11.148901,1.757558,0.681772,10.475566,9.121415
min,19.000000,55.0000,48.900000,49.900000,1.000000,0.000000,41.900000,52.066667
25%,20.000000,75.7750,72.300000,73.100000,3.400000,0.000000,64.050000,70.733333
50%,21.000000,82.7000,78.650000,80.250000,4.500000,0.000000,70.850000,76.466667
75%,21.000000,89.3000,85.400000,88.625000,5.800000,1.000000,77.925000,83.000000
max,23.000000,100.0000,100.000000,100.000000,10.000000,4.000000,100.000000,100.000000

In [53]:
print(data['Internal_Mark'].mean())

80.43780000000001

In [54]:
print(data['Internal_Mark'].median())

80.25

In [55]:
print(data['Internal_Mark'].mode())

0    100.0
Name: Internal_Mark, dtype: float64